export const AuthenActionType =
{
    FETCH_LOGIN_IN_PROGRESS: 'FETCH_LOGIN_IN_PROGRESS',
    FETCH_LOGIN_SUCCESS: 'FETCH_LOGIN_SUCCESS',
    FETCH_LOGIN_FAILED: 'FETCH_LOGIN_FAILED',

    FETCH_LOGOUT_SUCCESS: 'FETCH_LOGIN_SUCCESS'
}

export const MemberActionType =
{
    FETCH_MEMBER_LIST_IN_PROGRESS: 'FETCH_MEMBER_LIST_IN_PROGRESS',
    FETCH_MEMBER_LIST_SUCCESS: 'FETCH_MEMBER_LIST_SUCCESS',
    FETCH_MEMBER_LIST_FAILED: 'FETCH_MEMBER_LIST_FAILED',

    FETCH_MEMBER_DETAIL_SUCCESS: 'FETCH_MEMBER_DETAIL_SUCCESS',
    DELETE_MEMBER_SUCCESS: 'DELETE_MEMBER_SUCCESS'
}
